### ISSUE TITLE
cave-in dropping bricks

### ISSUE THREAD

**Issue by shawnm355** [asiekierka/UnlimitedChiselWorks-TFC1#1]
ok this is a weird one.i was messing around in a cave under a hotspring when i triggerd a cavein. and the marbel turned into cobble bricks
![2019-12-16_14 21 26](https://user-images.githubusercontent.com/34388628/70936423-3e98fa80-2010-11ea-8898-c9ed0b4e252f.png)

this is weird cause i cant reproduse it

anyway hope you can figure this out thanks

**Comment by asiekierka** [comment]
Fixed in 0.1.1.

**Comment by MagmaSlime123** [comment]
> Fixed in 0.1.1.

Read #3.
