### ISSUE TITLE
All blocks do not exist.

### ISSUE THREAD

**Issue by MagmaSlime123** [asiekierka/UnlimitedChiselWorks-TFC1#3]
Title. None of this mod's blocks exist in any of the Creative inventory tabs. TFC or Chisel tabs included.

**Comment by asiekierka** [comment]
Did you install the base Unlimited Chisel Works mod? The addon alone won't work.

**Comment by MagmaSlime123** [comment]
Yes. Also have this issue with the base mod. Almost none of its blocks exist.
https://github.com/asiekierka/UnlimitedChiselWorks/issues/75

**Comment by MagmaSlime123** [comment]
God I hate configs. Config issue on my part. Please split UCW's config from Chisels.
